# Generated by Django 2.2.12 on 2020-04-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
        ('users', '0002_auto_20200427_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_test', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='user',
            name='testt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_testt', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='user',
            name='testtt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_testtt', to='home.CustomText'),
        ),
    ]
