# Generated by Django 2.2.12 on 2020-04-27 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customtext_test'),
        ('users', '0003_auto_20200427_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcgv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fcgv', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='user',
            name='fsrtfhgv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fsrtfhgv', to='home.HomePage'),
        ),
    ]
